### ISSUE TITLE
Use of newer webhook API by GitHub Actions

### ISSUE THREAD

**Issue by mohawk2** [kan/coveralls-perl#34]
This module uses the v1 API that needs the repo token configured by some means, as shown in #33. However, looking at https://github.com/coverallsapp/github-action/blob/master/src/run.ts#L51 it appears that there is another way for GH actions: to use Coveralls's webhook endpoint, which uses as its `repo_token` the `GITHUB_TOKEN` that, crucially, is already available. Are you open to a PR adding this capability, probably dispatched on a `GITHUB_TOKEN` env var?

This would mean https://github.com/eserte/graphviz-makefile/issues/4 and https://github.com/neilb/Graph/issues/16 wouldn't be needed (at least to get Coveralls working).

**Comment by kan** [comment]
> Are you open to a PR adding this capability, probably dispatched on a GITHUB_TOKEN env var?

Yes. You are right. PR's welcome.

**Comment by mohawk2** [comment]
It turns out that I was reading the code a bit wrong: the `/webhook` is only used to report parallel jobs are finished.

The reason that Coveralls works right using the `/v1` API endpoint when setting the `repo_token` to the value of the secret `GITHUB_TOKEN` is almost certainly because it special-cases when the `service_name` is `github` (unlike your current code which sets it to `github-actions`). Therefore I have added to #33 to make this work correctly, but am closing this issue as its premise was wrong :-)
